language: node_js

node_js:
    - '0.12'

notifications:
    email: false

cache:
  directories:
    - $HOME/.npm

before_script:
    - 'npm install -g grunt-cli'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
